microsoft/clarity

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-decode/src/data.ts
- packages/clarity-decode/src/interaction.ts
- packages/clarity-decode/src/layout.ts
- packages/clarity-decode/types/layout.d.ts
- packages/clarity-devtools/package.json
- packages/clarity-devtools/src/content.ts
- packages/clarity-devtools/src/panel.ts
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/config.ts
- packages/clarity-js/src/core/index.ts
- packages/clarity-js/src/core/report.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/limit.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/src/interaction/click.ts
- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/src/layout/selector.ts
- packages/clarity-js/src/layout/target.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/interaction.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/layout.ts
- Change ids to be string instead of number
- Add selector field to Click event for debugging
- Capture text for non-link elements too
- Limit click text to 25 characters (configured by Setting)
- Remove backward compatibility for .next field while parsing DOM
- Fixing bug to compute selector correctly during decode logic
- Removing id field from computing selector
> Change ids to string and selector bug fixes

- packages/clarity-js/src/layout/mutation.ts
We are running into an issue with styled-components. The current wrapper of insertRule breaks styled components when there is invalid css. Note that invalid css also includes css that is valid in firefox but not chrome.
For example: `.kcpktl::-moz-placeholder{color:#959EA8;}` should raise an error but in the current implementation it does not. This is valid in firefox, but not in chrome.
In styled-components it is expected that insertRule raises an exception when there is an error and does not increment index in that case.  See the following code:
https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/sheet/Tag.js#L35-L43
The solution here is to raise the original error back that the caller can catch on …
> Reraise Error in insertRule wrapper to fix styled-components

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/history.ts
- packages/clarity-js/src/core/task.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
In an edge case it's possible for Angular + Clarity to get stuck into infinite mutation loop. Early investigation suggests it could be due to the way Zone.js overrides MutationObserver API. This fix is to utilize native browser API and therefore prevent side effects. A related issue that has more details: https://github.com/angular/angular/issues/31712
> Using native browser API for MutationObserver

- packages/clarity-js/src/core/scrub.ts
When a user clicks an existing input box and clicks out of it, even with mask tag set to true, data was being sent as unmasked.
> Handle case when user clicks an input that has data in it

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/config.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/metric.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
- Moving to session cookie instead of session storage since it's unreliable on iOS Safari
- Bumping up the version to 0.6.11
- Adding support for TabId as part of a dimension (still through Session Storage)
- Updating cookie handling to be forward compatible for future changes
> Changes to sessionization logic and price extraction

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/metric.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/src/layout/schema.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/data.ts
- Better handle unexpected payloads in JSON+LD
- Use cookie instead of session storage for session - so we can track cross tabs
- Fall back to sendBeacon when XHR return status code = 0 (on page getting unloaded). Impacts Safari.
> JSON+LD fixes and moving sessionization to use cookies

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/encode.ts
- packages/clarity-js/src/global.ts
- packages/clarity-visualize/package.json
- yarn.lock
Playback is set from upload when we send > 0 dom bytes - removing the metric when calling upgrade, since we could upgrade but the client might not send any playback data
> Do not track playback until we send back more than 0 dom bytes

- packages/clarity-js/types/index.d.ts
I noticed a typing error (typescript) when using clarity.
It seems that this stop function
https://github.com/microsoft/clarity/blob/65aa9401def813f83f82bae3c4d853b667b85405/packages/clarity-js/src/clarity.ts#L47
is being declared as clarity.end in the typescript typing definition. This error came when using the clarity module for ourselves from npm inside of our typescript project.
> Fix Clarity Interface Typing Error

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/global.ts
- packages/clarity-visualize/package.json
Set a "v" property on the global clarity variable so we can look for it before running a second instance.
> Prevent running multiple instances of Clarity simultaneously

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
- Extension session cookie to store server information and make it forward and backward compatible for future.
- Remove backward compatibility code from 0.6.11 that is no longer needed
> Persisting server location as part of session information

- lerna.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/variable.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/src/layout/schema.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/heatmap.ts
- packages/clarity-visualize/src/layout.ts
- packages/clarity-visualize/types/visualize.d.ts
Fixes the following issues 
1. Heatmap does not work for elements inside shadow dom
2. Scroll map height is not set properly 
3. Scrollmap canvas crashes for pages with a very large height 
4.  Custom variables are overriden in some cases and appended in others
5. Add Json+LD for article headlines and creators
> bug fix: heatmap issues, custom variables

- packages/clarity-js/src/layout/mutation.ts
This PR changes `attachShadow` patching for `HTMLElement.prototype` to `Element.prototype`. This will match closer to the DOM specification as the `attachShadow` method is defined on the Element interface and will mitigate interoperability issues with other 3rd-party libraries patching the same API.
Fixes #192.
> Patch `attachShadow` on `Element.prototype`

- packages/clarity-js/src/data/upload.ts
This PR has 2 main changes: 
- Bind the sendBeacon function to the navigator object before passing the reference.
- Surround the sendBeacon function call with a try catch bloc to catch the url parsing errors.
This PR fixes the issue #194
> Refactor the send payload function

- packages/clarity-js/src/core/timeout.ts
- packages/clarity-js/src/layout/mutation.ts
Added timeout to the document dimensions computing function. This function is called after the mutation is processed. this timeout without delays is added in order for this function to be at the end of the queue and executes after all the changes in the dom are done
https://stackoverflow.com/questions/19815810/avoiding-html-document-reflows
https://gist.github.com/paulirish/5d52fb081b3570c81e3a
> add timeout to document dimensions computing in order to be executed after all the changes in the dom are done

- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/types/layout.d.ts
Exclude svg:style children text nodes from masking. hence will be treated like style and title tags
> Account for svg:style when masking

- packages/clarity-js/src/layout/node.ts
It may be related to issues #208, #254 and #279 as well.
What kind of change does this PR introduce?
Bugfix
As described at the issue #279, Clarity is not accessing relative address correcly.
I believe this is happening because currently, clarity is always creating a base tag with the base address of the page.
When a page doesn't have a `<base>` tag, browsers will always access relative resources through the page full path (not the base url).
- A base tag will only be added in case the page does not contains one.
- When loading iframes, it will add the iframe 'src' value as base tag (in case the iframe does not  contains a base tag).
- When there's no base tag, a tag will be added with the full path, in order to correctly replicate browsers behavior (when there is no base tag).
I've …
> Added pathname in order to correctly load relative path address.

- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/src/performance/observer.ts
This pull request proposes some changes to improve the functionality of clarity-js on websites deployed on ports different than port 80 and port 443.
Currently, version 0.7.4 of clarity-js does not work properly on websites deployed on ports other than 80 and 443. For instance, when using clarity-js on a website deployed on port 8443, recordings and heatmaps won't work properly because clarity will try to download static assets from `example.com` instead of `example.com:8443`.
After reviewing the code, I found out that `hostname` was used in three instances instead of host, which causes the issues described above. Therefore, this pull request suggests replacing `hostname` with host in the relevant code blocks.
The proposed changes are backwards compatible because if no port is specified, …
> fix(clarity-js): replaces hostname with host containing port

- packages/clarity-visualize/src/layout.ts
May related to #278, #329, or any project build with webpack/angular or have external font URL in the CSS file.
The CSS files caching with URL `https://clarity.microsoft.com/external/v2/resources?url={url}` (1) have the content replaced with external resource URL but *SHA-384 integrity* itself aren't updated, causing resource blocked by browser.
You can run diff check on the URL (1) and original URL on any CSS file with `@font-face { src: url(...) }`.
Or play any recording which has CSS issue, then open DevTools (F12), go to Console, then paste the following:
```js
document.querySelector('#clarity-snapshot-iframe')
.contentDocument.querySelectorAll('link[integrity]')
.forEach(ln => {
ln.removeAttribute('integrity');
ln.href= ln.href;
});
```
> Remove integrity attribute for proxy <link />, potential fix for CSS sub-resources integrity.

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-visualize/package.json
Some browsers automatically url encode cookie values if they are not url encoded. We fix this by always uri encoding cookies, and supporting the decoding of encoded cookies.
> Uri encode cookie values for compatibility with certain mobile browsers

- packages/clarity-js/types/data.d.ts
Add a separate client dimension to be used by Apps SDKs to contain the device model e.g. Pixel 6 Pro.
Note: It's confusing but the existing Model dimension cannot be used as it's already been used to capture the device brand.
> Add DeviceFamily to client Dimension

- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-visualize/package.json
Some css relies on specific number of children or position of children within a DOM tree. Adding noscript tags into our visualized DOM to maintain correctness.
> Adding noscript placeholders

- lerna.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-visualize/package.json
Ignoring big base64 encoded src for video and audio html tags to prevent large payload tokens and memory leaks.
Addressing [this issue](https://github.com/microsoft/clarity/issues/407#issuecomment-1992055905)
> Ignoring src in media tags

- packages/clarity-js/src/data/metadata.ts
Writing zero as our time was making it a session cookie, switching to negative max value to ensure it is expiring and adding some extra validation to ensure we don't start writing cookies again for subsequent calls until consent is captured.
> ensuring we clear out cookie values when consent is revoked

- packages/clarity-js/src/interaction/click.ts
Provided we have an element with the following conditions:
- has no text content
- has a non-string value (e.g. number)
Then clarity throws an error when interacting with that element
The following error is thrown and logged:
```
TypeError: n.replace is not a function
at fn (clarity.js:2:26237)
at dn (clarity.js:2:26080)
at HTMLDocument.<anonymous> (clarity.js:2:56206)
at HTMLDocument.sentryWrapped (helpers.ts:100:1)
```
This points to the following code ([link](https://github.com/microsoft/clarity/blob/c8cb2cc3c01bdc5b96c34d72b3dfe5cec535e68b/packages/clarity-js/src/interaction/click.ts#L93):
```js
function text(element: Node): string {
let output = null;
if (element) {
// Grab text using "textContent" for most HTMLElements, however, use "value" for HTMLInputElements and "alt" for …
```
> fix: non-string form input values on click interaction

- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/types/data.d.ts
Metadata callbacks with `!wait` flag are executed once and not added to the list of callbacks in case another session starts for the same page.
> Fix metadata callbacks for long/multiple sessions

- packages/clarity-decode/src/data.ts
- packages/clarity-js/src/data/baseline.ts
- packages/clarity-js/src/data/encode.ts
- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/types/data.d.ts
- Added pointer move X, Y coordinates and time to the baseline data structure to track pointer movement during user interactions.
- - Added pointer down X, Y coordinates and time to the baseline data structure to track pointer down during user interactions.
- Added pointer time to the baseline data structure to track the time of pointer movement during user interactions.
> Extend baseline to hold pointer move data

- packages/clarity-decode/src/interaction.ts
- packages/clarity-js/src/interaction/click.ts
- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/types/interaction.d.ts
- Add new field to denote if text is full length or partial in click event
- Updated deprecated `substr` with `substring` method
> Add flag for click text length

- packages/clarity-decode/src/data.ts
- packages/clarity-js/src/data/baseline.ts
- packages/clarity-js/src/data/encode.ts
- packages/clarity-js/types/data.d.ts
- adding support for tracking the previous pointer positions and times, as well as the coordinates and times of mouse up events.
> Extend baseline data to hold more pointer info

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-visualize/package.json
Introduces a new `observedNodes` map in the `mutation.ts` file to ensure duplicate observers are not added to same node.
> Fix memory leak issues with mutation observers

- packages/clarity-js/src/insight/snapshot.ts
- packages/clarity-js/src/layout/target.ts
- packages/clarity-js/types/layout.d.ts
Simplified metadata structure by eliminating unnecessary properties.
> Remove unused node param from TargetMetadata

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/event.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-visualize/package.json
Currently, Clarity is not removing event listeners when observed nodes are removed. This leads to a memory leak issue as the event listeners are not properly cleaned up.
- Refactored event binding to use a `Map` for better management of event listeners and added a new `unbind` function to remove event listeners from specific targets.
- Replaced `observers` array with a `Set` in `mutation.ts` for better management of mutation observers. Added `disconnect` function to handle observer disconnections. 
- Added `iframeContentMap` in `dom.ts` to map iframe elements to their content documents and windows. Introduced `iframeContent`, `removeIFrame`, and `ignore` functions to manage iframe-related data and event listeners.
> Address memory leak issue with event listeners

- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/types/data.d.ts
Changes to support caret (`^`) separator as well in cookie. The updates ensure backward compatibility with the previous separator.
>  Support Caret as separator in cookie

- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/src/interaction/pointer.ts
- Only primary pointer (when available) events should update the baseline state. 
- Pointer “debouncing” should be pointer identifier aware.
> Enhance event tracking logic and improve pointer state comparison

- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/types/data.d.ts
In lean mode, Clarity keeps collecting playback data and keeps it in memory. When it reaches a limit, currently set at 10MB, it shuts down completely. Even `upgrade` signal is ignored afterwards. This changes the behavior to pause collecting playback data before the limit is reached so that other telemetry keeps getting sent and `upgrade` will still be supported.
_Limitation: mutations happening during the pause will be lost._
> Stop collecting playback data after limit is reached in lean mode

- packages/clarity-js/src/layout/region.ts
the `rootBounds` of `IntersectionObserverEntry` is possible to be `null` (ref: https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/rootBounds), so we need to check if it's `null` before using it
I've already seen a lot of such errors around, so I think it's a good idea to add the check here.
> viewport null check

- .gitignore
- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/throttle.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/interaction/pointer.ts
- packages/clarity-js/src/interaction/scroll.ts
- packages/clarity-js/types/interaction.d.ts
- packages/clarity-visualize/package.json
This pull request introduces a throttling mechanism to improve the performance of scroll event handling in the `clarity-js` package. The most important changes include the addition of a reusable `throttle` utility function, its integration into the scroll event observer, and the replacement of the unthrottled `recompute` function with a throttled version.
> Add throttling for scroll, increase interval for similar events (0.8.11)

- packages/clarity-decode/rollup.config.ts
- packages/clarity-js/rollup.config.ts
- packages/clarity-js/src/layout/style.ts
- packages/clarity-visualize/rollup.config.ts
This pull request updates the handling of `package.json` imports in Rollup configuration files, fixes a plugin array issue in `clarity-js`, and removes an unused import in `clarity-js` source code. 
Replaced the `assert { type: 'json' }` syntax for importing `package.json` with `fs.readFileSync` and `JSON.parse` in `rollup.config.ts`. This ensures compatibility with newer NodeJS versions that dropped support for `assert` syntax.
> Support for node v23

- packages/clarity-js/src/data/upload.ts
This pull request introduces a minor enhancement to improve error reporting during upload retries.
> Capture failure status before upload re-attempt

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/consent.ts
- packages/clarity-js/src/data/index.ts
- packages/clarity-visualize/package.json
- Resetting permission to send payload whenever Clarity stops and restarts
- Whenever consent was denied, a session was suspended, or the site was an SPA i.e whenever clarity stopped and restarted, updateConsent was not reset and subsequent pages did not send the consent event.
> Add Consent Stop and Start (0.8.23)

- packages/clarity-js/src/clarity.ts
- packages/clarity-js/src/data/upload.ts
- Expose `task.schedule` for use in dynamic modules
> Move animation event to playback property in payload
