microsoft/clarity

- lerna.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/clarity.ts
- packages/clarity-visualize/src/interaction.ts
- Changing pointer
- Adding canvas support to show mouse trail
- Adding ripple effect around click
> Playback visualization update

- lerna.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/interaction.ts
- Bug fixes in pointer playback
> Adding support for multiple touch points

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/src/panel.ts
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/interaction/resize.ts
- packages/clarity-js/src/layout/discover.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/clarity.ts
- packages/clarity-visualize/src/interaction.ts
- packages/clarity-visualize/src/layout.ts
- packages/clarity-visualize/types/index.d.ts
- packages/clarity-visualize/types/visualize.d.ts
- Removing initial delay in visualization that could last for several milliseconds
- Fixing the timestamp that we send back with DOM events (discover, mutation)
- Handling visualization of IFRAME
- Adding hover support during visualization
- Fixing the code to grab viewport width & height
> Visualization improvements and bug fixes

- packages/clarity-decode/src/diagnostic.ts
- packages/clarity-decode/src/interaction.ts
- packages/clarity-js/src/core/measure.ts
- packages/clarity-js/src/core/task.ts
- packages/clarity-js/src/data/index.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/metric.ts
- packages/clarity-js/src/diagnostic/encode.ts
- packages/clarity-js/src/interaction/baseline.ts
- packages/clarity-js/src/interaction/click.ts
- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/src/layout/region.ts
- packages/clarity-js/src/layout/target.ts
- packages/clarity-js/src/performance/observer.ts
Changes include
1. Bug fix for invoke count, task yield time,  relative position for clicks 
2. Track region info for clicks and Remove region for pointer and scroll events
> Track Region for clicks and other bug fixes 

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-decode/src/clarity.ts
- packages/clarity-devtools/package.json
- packages/clarity-devtools/src/content.ts
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/config.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/index.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/upgrade.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/src/layout/target.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
Also includes:
- Configuration to read custom cookies
- Upgrade the whole session instead of a single page
- Bumping up the package version
> Separating events for playback & analysis

- packages/clarity-js/src/data/metadata.ts
> metadata changes

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/envelope.ts
- packages/clarity-js/src/data/limit.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/upgrade.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
- Override config with session data
- Do not attempt retries if server returns 400 bad payload
> Data quality bug fixes

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/src/content.ts
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- Adding price information in JsonLD
- Updating metadata callback to fire when the session is upgraded
- Bug fixes to better handle dynamic stylesheets
> Bug fixes: JsonLD, Metadata callback and dynamic stylesheets

- packages/clarity-devtools/src/content.ts
- packages/clarity-js/src/core/history.ts
- packages/clarity-js/src/core/index.ts
- packages/clarity-js/src/core/task.ts
- packages/clarity-js/types/data.d.ts
Listen to change in history API to auto determine page boundaries within single page application.
> Support for single page applications

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-decode/src/layout.ts
- packages/clarity-devtools/package.json
- packages/clarity-devtools/src/regions.ts
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/history.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/interaction/click.ts
- packages/clarity-js/src/interaction/unload.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/src/layout/index.ts
- packages/clarity-js/src/layout/region.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/clarity.ts
- packages/clarity-visualize/src/layout.ts
- Dropping bounding rectangle for regions
- Using IntersectionObserver
- Updating decode logic to match new data schema
- Stop listening to unload event to not impact backward-forward cache
- Get clicked text from buttons, input fields as well as images
> Simplifying regions, performance improvements & bug fixes

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/interaction/scroll.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/region.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/interaction.ts
- packages/clarity-visualize/src/layout.ts
- packages/clarity-visualize/types/visualize.d.ts
- On hover visualization fix
- Rendering cross-origin iframe as blocked
- Accepting multiple regions per page
- Bug fixing race condition between region processing and DOM discovery
> Visualization updates and regions bug fixes

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/dimension.ts
- packages/clarity-js/src/data/metric.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/src/layout/schema.ts
- packages/clarity-js/src/performance/observer.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/data.ts
- Adding new fields
- Refactoring JSON+LD code to a separate module
- Data quality bug fixes
> Refactoring code to parse JSON+LD

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-devtools/static/panel.html
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/dimension.ts
- packages/clarity-js/src/layout/region.ts
- packages/clarity-js/src/performance/observer.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/clarity.ts
- packages/clarity-visualize/src/data.ts
- packages/clarity-visualize/src/interaction.ts
- packages/clarity-visualize/types/visualize.d.ts
- Better intersection inference
- Added support for region visualization in the extension
- Fix script error with performance observer in older browsers
> Improve region handling and bug fixes

- packages/clarity-js/src/layout/document.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-visualize/src/clarity.ts
- packages/clarity-visualize/types/index.d.ts
Visualize changes : 
1. Render html at a give time 
2. Get time of the current snapshot
Bug fix
1. Document width is 0 for some sites
> client changes for visualize and bug fix for document width

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/interaction.ts
if a website sets a background for all canvas  element, the visualization appears as a grey screen.
> reset canvas background

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/data/token.ts
- packages/clarity-js/src/diagnostic/internal.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
- Reducing computation complexity of tokenization logic
- Simplifying fields in session cookie by removing backward compatibility code
- Honor prior consent setting to persist tracking option for the user
> Performance optimizations

- packages/clarity-visualize/src/clarity.ts
- packages/clarity-visualize/types/index.d.ts
> export get hash

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-decode/src/clarity.ts
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/measure.ts
- packages/clarity-js/src/core/report.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/limit.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/src/layout/selector.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/index.d.ts
- packages/clarity-visualize/package.json
- Changing payload for report endpoint to make logging more actionable
- Update beta selector logic to improve data quality
- Bumping version to 0.6.28
> Bug fixes and monitoring updates

- packages/clarity-js/src/data/metadata.ts
Add a test before accessing the brands property. See #195 fore more information
> Fix #195 ua.brands is undefined

- packages/clarity-js/src/layout/selector.ts
- packages/clarity-visualize/src/layout.ts
- handle not only shadow DOM but also iframe DOM
> fix: beta selector

- packages/clarity-js/test/helper.ts
Hi Clarity team,
While I was helping my colleague reviewing the code base of this project, I found some issues in the included test cases in the clarity-js.
**Issue 1:**
The default page opened by playwright is `about:blank`. Access to document cookies is forbidden on the blank page.
This can be resolved by opening the testing HTML file using file url at the beginning of every test.
```diff
export async function markup(page: Page, file: string, override: Core.Config = null): Promise<string[]> {
-    const html = fs.readFileSync(path.resolve(__dirname, `./html/${file}`), 'utf8');
+    const htmlPath = path.resolve(__dirname, `./html/${file}`);
+    const htmlFileUrl = url.pathToFileURL(htmlPath).toString();
+    const html = fs.readFileSync(htmlPath, 'utf8');
+    await Promise.all([
+ …
```
> Fix clarity js test cases

- packages/clarity-js/src/core/history.ts
As said in the related issue, other 3rd party scripts might also proxy the History API. If Clarity completely removes its proxy of these methods, it could wipe out those 3rd parties that proxied the API after Clarity did (since Clarity takes its clean version of the methods when it proxies them--those clean methods won't have already been proxied by the 3rd party scripts).
So, Clarity should proxy these methods once and trigger its logic based on some enabled/disabled flag, but otherwise leaving the History API alone after it loads.
Issue #224
> Proxy the history API only once

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/scrub.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/interaction/pointer.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/test/core.test.ts
- packages/clarity-js/test/helper.ts
- packages/clarity-js/test/html/core.html
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- Addressing user feedback to adjust default masking capabilities
- Updating unit tests to reflect new logic
- Updating mousewheel -> wheel event for better browser compatibility
- Bumping up version to 0.6.38
> Masking logic update + bug fixes

- packages/clarity-visualize/src/interaction.ts
> append audio element to the DOM

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/scrub.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/interaction.ts
- Added a try / catch to fail gracefully in IE11
- Minor visualization update
> Bug fix: Older browser compatibility

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-decode/src/interaction.ts
- packages/clarity-decode/src/layout.ts
- packages/clarity-decode/types/layout.d.ts
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/index.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-js/src/layout/selector.ts
- packages/clarity-js/types/index.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/enrich.ts
- packages/clarity-visualize/src/layout.ts
- packages/clarity-visualize/types/visualize.d.ts
- Rename stable selector to alpha selector
- Change algorithm of how alpha selector is computed
- Few additional bug fixes
> Add support for alpha selector

- packages/clarity-visualize/src/layout.ts
- packages/clarity-visualize/src/visualizer.ts
- packages/clarity-visualize/types/visualize.d.ts
- Wait for stylesheets and fonts to load
- Null check layout
- Rename logger
> Wait styles to load and add a null check on layout

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/clarity.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/global.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-js/src/queue.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
- packages/clarity-visualize/src/layout.ts
- packages/clarity-visualize/src/visualizer.ts
- packages/clarity-visualize/types/visualize.d.ts
- Improve logic to determine which elements get suspended from continuous mutations
- Better queuing while Clarity is stopped or suspended
- Visualization improvements to handle third party resources
> Bug fixes based on user feedback

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-decode/src/data.ts
- packages/clarity-devtools/package.json
- packages/clarity-devtools/src/config.ts
- packages/clarity-devtools/src/content.ts
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/config.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/encode.ts
- packages/clarity-js/src/data/extract.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/src/layout/dom.ts
- packages/clarity-js/src/layout/mutation.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
> extract changes

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-visualize/package.json
augmenting consent api to enable webmasters to indicate consent was revoked. will clear cookies and start a new clarity session
> Consent Revoked API

- lerna.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/region.ts
- packages/clarity-js/types/layout.d.ts
- packages/clarity-visualize/package.json
Process all elements in the queue if an element is not discovered already when processing region events
> process all states from region queue

- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/clarity.ts
- packages/clarity-js/src/core/config.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/index.ts
- packages/clarity-js/src/layout/node.ts
- packages/clarity-js/types/core.d.ts
- packages/clarity-visualize/package.json
delaying the layout module after DOM finish loading. This is part of our experiments that target optimizing the initial page load time.
> Delay layout module experiment

- lerna.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/baseline.ts
- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
track last scroll time in baseline data
> track last scroll time in baseline data

- packages/clarity-decode/src/data.ts
- packages/clarity-decode/src/interaction.ts
- packages/clarity-js/src/interaction/scroll.ts
add token length check for backward compatibility.
sending first scroll event so we can get the initial top & bottom element
> add token length check for backward compatibility.

- packages/clarity-decode/src/interaction.ts
- packages/clarity-js/src/interaction/encode.ts
- packages/clarity-js/src/interaction/pointer.ts
- packages/clarity-js/types/interaction.d.ts
Add touch identifier to pointer data to handle multi-touch screens
Ref: https://www.w3.org/TR/touch-events/#widl-Touch-identifier
> Add id to pointer data to handle multi-touch screens

- packages/clarity-js/src/layout/mutation.ts
- Improve code readability and maintainability
- Enhance mutation processing logic to ignore mutations triggered by certain unused attributes
> Ignore mutations from unused attributes

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/layout/encode.ts
- packages/clarity-visualize/package.json
as sometimes they are cleared out via setting innerHTML to empty string
> ensuring we process empty values for style nodes 

- packages/clarity-js/src/data/metadata.ts
This reverts commit dd97ccfea83851838d6bdea50382271552b76124.
> Revert "Replace pipe with caret as separator in cookie (#820)"

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/api.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
Logging to capture when Angular + Zone is used in the Websites.
> Log to capture Angular + Zone usage

- packages/clarity-js/src/core/report.ts
This reverts commit 1cc54c7bf12f1e35fe007968fd41faa27f5babdd.
> Revert "null check for envelope data (#850)"

- packages/clarity-js/src/layout/region.ts
This reverts commit 880e542de262d550a5c50a49e47b52570a5e4c7f.
> Revert "viewport null check (#846)"

- packages/clarity-decode/src/clarity.ts
- packages/clarity-decode/src/data.ts
- packages/clarity-decode/types/data.d.ts
- packages/clarity-js/src/clarity.ts
- packages/clarity-js/src/data/consent.ts
- packages/clarity-js/src/data/encode.ts
- packages/clarity-js/src/data/index.ts
- packages/clarity-js/src/data/metadata.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-js/types/index.d.ts
> Revert "Update Consent Api"

- packages/clarity-js/src/performance/observer.ts
This pull request optimizes performance and memory management in the `host` function of the `observer.ts` file by introducing an anchor element cache. Additionally, it ensures the cache is reset when the `stop` function is called.
> Optimize perf & memory mgmt in host function

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-visualize/package.json
- scripts/bump-version.ts
This pull request updates the project version from `0.8.15` to `0.8.16`, and enhances the version bump script to preserve the original line ending style.
> Bump version to 0.8.16

- packages/clarity-js/src/core/throttle.ts
- packages/clarity-js/src/core/time.ts
- packages/clarity-js/src/data/encode.ts
- packages/clarity-js/src/interaction/scroll.ts
- Added a cleanup method to the `throttle` function ensuring proper cleanup in the scroll interaction module
- Refactored time computation logic, ensuring relative timing semantics are maintained even when `startTime` is zero
- Added null check for Baseline event encoding
> Enhance throttle function to include cleanup method

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
This pull request updates the project version from `0.8.20` to `0.8.21` and introduces an enhancement to error handling in the `sendBeacon` method.
> Capture and report sendBeacon errors (0.8.21)

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/interaction/resize.ts
- packages/clarity-visualize/package.json
Refactored the resize handling logic in `packages/clarity-js/src/interaction/resize.ts` to improve performance by introducing throttling for the resize event handler.
> Throttle resize event (0.8.22)

- packages/clarity-js/src/clarity.ts
- packages/clarity-js/src/core/dynamic.ts
- packages/clarity-js/src/data/upload.ts
- packages/clarity-js/types/data.d.ts
This pull request introduces dynamic module loading capabilities to the codebase, allowing scripts to be loaded and managed at runtime. It adds a new `dynamic` module, exposes related functions for external use, and integrates dynamic event handling into the upload response flow.
> Add support for dynamic loading of new modules

- .github/workflows/npm-publish.yml
- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/clarity.ts
- packages/clarity-js/src/core/version.ts
- packages/clarity-js/src/data/index.ts
- packages/clarity-js/types/data.d.ts
- packages/clarity-visualize/package.json
- Expose max metric function
- Disable auto release workflow
> Export max metric function

- lerna.json
- package.json
- packages/clarity-decode/package.json
- packages/clarity-devtools/package.json
- packages/clarity-devtools/static/manifest.json
- packages/clarity-js/package.json
- packages/clarity-js/src/core/version.ts
- packages/clarity-visualize/package.json
> Bump version to 0.8.33
